/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansAgenda;
import modeloConection.ConexaoBD;
import modeloDao.DaoClientes;
import modeloBeans.BeansClientes;
import modeloBeans.ModeloTabelaCli;
import modeloDao.DaoAgenda;
import java.util.Date;




/**
 *
 * @author Buzato
 */
public class CadastroEntrega extends javax.swing.JFrame {

        BeansClientes mod = new BeansClientes();
        DaoClientes control = new DaoClientes();
        ConexaoBD conex = new ConexaoBD();
        BeansAgenda agenda = new BeansAgenda();
        
    
    public CadastroEntrega() {
        initComponents();
        preencherTabela("select *from clientes order by cli_rzsocial" );
        preecherFuncionarios();
        preecherClientes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadEntrega = new javax.swing.JPanel();
        jLabelEntDataEntre = new javax.swing.JLabel();
        jLabelEntNomFunc = new javax.swing.JLabel();
        jComboBoxEntTurno = new javax.swing.JComboBox<>();
        jButtonEntSalvar = new javax.swing.JButton();
        jButtonEntCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntPesq = new javax.swing.JTable();
        jLabelEntTurno = new javax.swing.JLabel();
        jLabelEntLocEntega = new javax.swing.JLabel();
        jLabelEntCli = new javax.swing.JLabel();
        jComboBoxEntNomFunc = new javax.swing.JComboBox<>();
        jDateChooserEntDataEntre = new com.toedter.calendar.JDateChooser();
        jTextFieldDescricao = new javax.swing.JTextField();
        jComboBoxclinome = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabelFundoEntrega = new javax.swing.JLabel();
        jButtonfechar = new javax.swing.JButton();
        jLabelCadEntrega = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelCadEntrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadEntrega.setLayout(null);

        jLabelEntDataEntre.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntDataEntre.setText("Data Entrega.:");
        jPanelCadEntrega.add(jLabelEntDataEntre);
        jLabelEntDataEntre.setBounds(640, 230, 100, 30);

        jLabelEntNomFunc.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntNomFunc.setText("Nome Funcionario.:");
        jPanelCadEntrega.add(jLabelEntNomFunc);
        jLabelEntNomFunc.setBounds(130, 230, 130, 30);

        jComboBoxEntTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));
        jPanelCadEntrega.add(jComboBoxEntTurno);
        jComboBoxEntTurno.setBounds(740, 50, 140, 30);

        jButtonEntSalvar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonEntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cloud 2.png"))); // NOI18N
        jButtonEntSalvar.setText("Salvar Agendamento");
        jButtonEntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntSalvarActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonEntSalvar);
        jButtonEntSalvar.setBounds(260, 400, 210, 30);

        jButtonEntCancelar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonEntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButtonEntCancelar.setText("Cancelar Agendamento");
        jButtonEntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntCancelarActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonEntCancelar);
        jButtonEntCancelar.setBounds(670, 400, 210, 30);

        jTableEntPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEntPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntPesqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEntPesq);

        jPanelCadEntrega.add(jScrollPane1);
        jScrollPane1.setBounds(260, 90, 620, 120);

        jLabelEntTurno.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntTurno.setText("Turno de entrega:");
        jPanelCadEntrega.add(jLabelEntTurno);
        jLabelEntTurno.setBounds(620, 50, 120, 30);

        jLabelEntLocEntega.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntLocEntega.setText("Local Entrega / descrição Carga.:");
        jPanelCadEntrega.add(jLabelEntLocEntega);
        jLabelEntLocEntega.setBounds(260, 260, 220, 30);

        jLabelEntCli.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntCli.setText("Nome /Rz.Social Cliente.:");
        jPanelCadEntrega.add(jLabelEntCli);
        jLabelEntCli.setBounds(100, 50, 160, 30);

        jComboBoxEntNomFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelCadEntrega.add(jComboBoxEntNomFunc);
        jComboBoxEntNomFunc.setBounds(260, 230, 200, 30);
        jPanelCadEntrega.add(jDateChooserEntDataEntre);
        jDateChooserEntDataEntre.setBounds(740, 230, 140, 30);
        jPanelCadEntrega.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(260, 280, 630, 120);

        jComboBoxclinome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelCadEntrega.add(jComboBoxclinome);
        jComboBoxclinome.setBounds(260, 50, 240, 30);

        jButton1.setText("Gerar Ralatorio PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButton1);
        jButton1.setBounds(950, 0, 127, 40);

        jLabelFundoEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos-para-fotos-verde (3).jpg"))); // NOI18N
        jPanelCadEntrega.add(jLabelFundoEntrega);
        jLabelFundoEntrega.setBounds(0, 0, 1080, 440);

        getContentPane().add(jPanelCadEntrega);
        jPanelCadEntrega.setBounds(30, 40, 1080, 440);

        jButtonfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButtonfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonfechar);
        jButtonfechar.setBounds(1083, 10, 20, 25);

        jLabelCadEntrega.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabelCadEntrega.setText("Agendamento de Entrega");
        getContentPane().add(jLabelCadEntrega);
        jLabelCadEntrega.setBounds(470, 10, 311, 19);

        setSize(new java.awt.Dimension(1130, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntSalvarActionPerformed
        
        agenda.setNomecli((String) jComboBoxclinome.getSelectedItem());
        agenda.setNomeFunc((String) jComboBoxEntNomFunc.getSelectedItem());
        agenda.setTurno((String) jComboBoxEntTurno.getSelectedItem());
        agenda.setDescricao(jTextFieldDescricao.getText());
        agenda.setData(new java.sql.Date(jDateChooserEntDataEntre.getDate().getTime()));
        agenda.setStatus("Aberto");
        DaoAgenda dao = new DaoAgenda();
        dao.salavar(agenda);
        // Limpando os campos.
       
        jTextFieldDescricao.setText("");
        
        // Deixando campos que recebem itens nulo.
        jComboBoxEntNomFunc.setSelectedItem(null);
        jComboBoxclinome.setSelectedItem(null);
        jComboBoxEntTurno.setSelectedItem(null);
        jDateChooserEntDataEntre.setDate(null);
    }//GEN-LAST:event_jButtonEntSalvarActionPerformed

    private void jButtonfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfecharActionPerformed

        dispose();
    }//GEN-LAST:event_jButtonfecharActionPerformed

    private void jTableEntPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntPesqMouseClicked
        
        /*String nome_cliente =""+jTableEntPesq.getValueAt(jTableEntPesq.getSelectedRow(), 1);
        conex.Conexao();
        conex.Executasql("select *from clientes where cli_rzsocial='"+nome_cliente+"'");
            try {
                conex.rs.first();
                jTextFieldEntCli.setText(conex.rs.getString("cli_rzsocial"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "erro ao auto-completar!!\n"+ex);
            }
        conex.Desconecta();*/
    }//GEN-LAST:event_jTableEntPesqMouseClicked

    private void jButtonEntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntCancelarActionPerformed
         // Limpando os campos.
       
        jTextFieldDescricao.setText("");
        
        // Deixando campos que recebem itens nulo.
        jComboBoxEntNomFunc.setSelectedItem(null);
        jComboBoxclinome.setSelectedItem(null);
        jComboBoxEntTurno.setSelectedItem(null);
        jDateChooserEntDataEntre.setDate(null);
    
    }//GEN-LAST:event_jButtonEntCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

        public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] coluns = new String[]{"ID","CNPJ/CPF","RzSocial/Nome","Endereço"};
        conex.Conexao();
        conex.Executasql(Sql);
        try{
        conex.rs.first();
        do{
            dados.add(new Object[]{conex.rs.getInt("cod_cliente"),conex.rs.getString("cli_cnpj"),conex.rs.getString("cli_rzsocial"),conex.rs.getString("cli_end")});
        }while(conex.rs.next());
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro ao preencher array list"+ex.getMessage());
        
        } 
        ModeloTabelaCli modelo = new ModeloTabelaCli(dados, coluns);
        jTableEntPesq.setModel(modelo);
        jTableEntPesq.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableEntPesq.getColumnModel().getColumn(0).setResizable(false);
        jTableEntPesq.getColumnModel().getColumn(1).setPreferredWidth(102);
        jTableEntPesq.getColumnModel().getColumn(1).setResizable(false);
        jTableEntPesq.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTableEntPesq.getColumnModel().getColumn(2).setResizable(false);
        jTableEntPesq.getColumnModel().getColumn(3).setPreferredWidth(245);
        jTableEntPesq.getColumnModel().getColumn(3).setResizable(false);
        jTableEntPesq.getTableHeader().setReorderingAllowed(false);
        jTableEntPesq.setAutoResizeMode(jTableEntPesq.AUTO_RESIZE_OFF);
        jTableEntPesq.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.Desconecta();
    }
        public void preecherFuncionarios(){

            conex.Conexao();
            conex.Executasql("select *from funcionarios order by func_nome");
            try {
                conex.rs.first();
                jComboBoxEntNomFunc.removeAllItems();
                do{
                    jComboBoxEntNomFunc.addItem(conex.rs.getString("func_nome"));
                }while(conex.rs.next());
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"erro ao ´preencher");
            }
            conex.Desconecta();

}
        public void preecherClientes(){

            conex.Conexao();
            conex.Executasql("select *from clientes order by cli_rzsocial");
            try {
                conex.rs.first();
                jComboBoxclinome.removeAllItems();
                do{
                    jComboBoxclinome.addItem(conex.rs.getString("cli_rzsocial"));
                }while(conex.rs.next());
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"erro ao ´preencher");
            }
            conex.Desconecta();

}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntCancelar;
    private javax.swing.JButton jButtonEntSalvar;
    private javax.swing.JButton jButtonfechar;
    private javax.swing.JComboBox<String> jComboBoxEntNomFunc;
    private javax.swing.JComboBox<String> jComboBoxEntTurno;
    private javax.swing.JComboBox<String> jComboBoxclinome;
    private com.toedter.calendar.JDateChooser jDateChooserEntDataEntre;
    private javax.swing.JLabel jLabelCadEntrega;
    private javax.swing.JLabel jLabelEntCli;
    private javax.swing.JLabel jLabelEntDataEntre;
    private javax.swing.JLabel jLabelEntLocEntega;
    private javax.swing.JLabel jLabelEntNomFunc;
    private javax.swing.JLabel jLabelEntTurno;
    private javax.swing.JLabel jLabelFundoEntrega;
    private javax.swing.JPanel jPanelCadEntrega;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEntPesq;
    private javax.swing.JTextField jTextFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
