/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;
import modeloConection.ConexaoBD;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabelaCli;
import modeloBeans.ModeloTabelaUsuario;
import modeloDao.DaoUsuarios;




/**
 *
 * @author Buzato
 */
public class CadastroUsuarios extends javax.swing.JFrame {

        BeansUsuario modu = new BeansUsuario();
        DaoUsuarios control = new DaoUsuarios();
        ConexaoBD conex = new ConexaoBD();
        int flag =0;
        
    
    public CadastroUsuarios() {
        initComponents();
        preencherTabela("select *from login order by usu_nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadEntrega = new javax.swing.JPanel();
        jLabelUsuNome = new javax.swing.JLabel();
        jLabelEntUsuTpSenha = new javax.swing.JLabel();
        jComboBoxUsuTpSenha = new javax.swing.JComboBox<>();
        jButtonUsuNovo = new javax.swing.JButton();
        jButtonUsuSalvar = new javax.swing.JButton();
        jButtonUsuCancelar = new javax.swing.JButton();
        jButtonUsuEditar = new javax.swing.JButton();
        jButtonUsuExcluir = new javax.swing.JButton();
        jTextFieldUsuPesquisa = new javax.swing.JTextField();
        jButtonUsuPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuPesquisa = new javax.swing.JTable();
        jFormattedTextFieldUsuNome = new javax.swing.JFormattedTextField();
        jLabelUsuSenha = new javax.swing.JLabel();
        jLabelUsuConfSenha = new javax.swing.JLabel();
        jPasswordFieldUsuConfSenha = new javax.swing.JPasswordField();
        jPasswordFieldUsuSenha = new javax.swing.JPasswordField();
        jTextFieldusucod = new javax.swing.JTextField();
        jLabelusucod = new javax.swing.JLabel();
        jLabelFundoEntrega = new javax.swing.JLabel();
        jLabelCadEntrega = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelCadEntrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadEntrega.setLayout(null);

        jLabelUsuNome.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelUsuNome.setText("Usuário.:");
        jPanelCadEntrega.add(jLabelUsuNome);
        jLabelUsuNome.setBounds(350, 130, 90, 30);

        jLabelEntUsuTpSenha.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelEntUsuTpSenha.setText("Tipo Usuário.:");
        jPanelCadEntrega.add(jLabelEntUsuTpSenha);
        jLabelEntUsuTpSenha.setBounds(320, 160, 100, 30);

        jComboBoxUsuTpSenha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretario(a)", "Administrador" }));
        jComboBoxUsuTpSenha.setEnabled(false);
        jPanelCadEntrega.add(jComboBoxUsuTpSenha);
        jComboBoxUsuTpSenha.setBounds(420, 160, 130, 30);

        jButtonUsuNovo.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jButtonUsuNovo.setText("Novo");
        jButtonUsuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuNovoActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuNovo);
        jButtonUsuNovo.setBounds(130, 220, 110, 30);

        jButtonUsuSalvar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cloud 2.png"))); // NOI18N
        jButtonUsuSalvar.setText("Salvar");
        jButtonUsuSalvar.setEnabled(false);
        jButtonUsuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuSalvarActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuSalvar);
        jButtonUsuSalvar.setBounds(130, 260, 110, 30);

        jButtonUsuCancelar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButtonUsuCancelar.setText("Cancelar");
        jButtonUsuCancelar.setEnabled(false);
        jButtonUsuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuCancelarActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuCancelar);
        jButtonUsuCancelar.setBounds(130, 300, 110, 30);

        jButtonUsuEditar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pencil.png"))); // NOI18N
        jButtonUsuEditar.setText("Editar");
        jButtonUsuEditar.setEnabled(false);
        jButtonUsuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuEditarActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuEditar);
        jButtonUsuEditar.setBounds(130, 340, 110, 30);

        jButtonUsuExcluir.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Remove.png"))); // NOI18N
        jButtonUsuExcluir.setText("Excluir");
        jButtonUsuExcluir.setEnabled(false);
        jButtonUsuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuExcluirActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuExcluir);
        jButtonUsuExcluir.setBounds(130, 380, 110, 30);
        jPanelCadEntrega.add(jTextFieldUsuPesquisa);
        jTextFieldUsuPesquisa.setBounds(280, 230, 440, 30);

        jButtonUsuPesquisa.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonUsuPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search 1.png"))); // NOI18N
        jButtonUsuPesquisa.setText("Pesquisar");
        jButtonUsuPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuPesquisaActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jButtonUsuPesquisa);
        jButtonUsuPesquisa.setBounds(730, 230, 120, 30);

        jTableUsuPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUsuPesquisa);

        jPanelCadEntrega.add(jScrollPane1);
        jScrollPane1.setBounds(280, 260, 620, 150);

        jFormattedTextFieldUsuNome.setEnabled(false);
        jFormattedTextFieldUsuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldUsuNomeActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jFormattedTextFieldUsuNome);
        jFormattedTextFieldUsuNome.setBounds(420, 130, 130, 30);

        jLabelUsuSenha.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelUsuSenha.setText("Senha.:");
        jPanelCadEntrega.add(jLabelUsuSenha);
        jLabelUsuSenha.setBounds(630, 130, 60, 30);

        jLabelUsuConfSenha.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelUsuConfSenha.setText("Confirmar senha.:");
        jPanelCadEntrega.add(jLabelUsuConfSenha);
        jLabelUsuConfSenha.setBounds(560, 170, 120, 13);

        jPasswordFieldUsuConfSenha.setEnabled(false);
        jPasswordFieldUsuConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldUsuConfSenhaActionPerformed(evt);
            }
        });
        jPanelCadEntrega.add(jPasswordFieldUsuConfSenha);
        jPasswordFieldUsuConfSenha.setBounds(690, 160, 140, 30);

        jPasswordFieldUsuSenha.setEnabled(false);
        jPanelCadEntrega.add(jPasswordFieldUsuSenha);
        jPasswordFieldUsuSenha.setBounds(690, 130, 140, 30);

        jTextFieldusucod.setEnabled(false);
        jPanelCadEntrega.add(jTextFieldusucod);
        jTextFieldusucod.setBounds(420, 100, 130, 30);

        jLabelusucod.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelusucod.setText("Cod Usuário.:");
        jPanelCadEntrega.add(jLabelusucod);
        jLabelusucod.setBounds(320, 100, 100, 30);

        jLabelFundoEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos-para-fotos-verde (3).jpg"))); // NOI18N
        jPanelCadEntrega.add(jLabelFundoEntrega);
        jLabelFundoEntrega.setBounds(0, 0, 1080, 440);

        getContentPane().add(jPanelCadEntrega);
        jPanelCadEntrega.setBounds(30, 40, 1080, 440);

        jLabelCadEntrega.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabelCadEntrega.setText("Cadastro de Usuários");
        getContentPane().add(jLabelCadEntrega);
        jLabelCadEntrega.setBounds(470, 10, 311, 19);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1083, 10, 20, 25);

        setSize(new java.awt.Dimension(1130, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuNovoActionPerformed
     
        flag=1;
        jFormattedTextFieldUsuNome.setEnabled(true);
        jPasswordFieldUsuConfSenha.setEnabled(true);
        jPasswordFieldUsuSenha.setEnabled(true);
        jComboBoxUsuTpSenha.setEnabled(true);
        jButtonUsuSalvar.setEnabled(true);
        jButtonUsuCancelar.setEnabled(true);
        jButtonUsuPesquisa.setEnabled(false);
        jButtonUsuNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonUsuNovoActionPerformed

    private void jButtonUsuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuSalvarActionPerformed
       
        if(flag == 1){
        modu.setUsuNome(jFormattedTextFieldUsuNome.getText());
        modu.setUsuSenha(jPasswordFieldUsuSenha.getText());
        modu.setUsutipo((String) jComboBoxUsuTpSenha.getSelectedItem());
        control.Salvar(modu);
        jFormattedTextFieldUsuNome.setText("");
        jTextFieldUsuPesquisa.setText("");
        jPasswordFieldUsuSenha.setText("");
        jPasswordFieldUsuConfSenha.setText("");
        jFormattedTextFieldUsuNome.setEnabled(false);
        jPasswordFieldUsuConfSenha.setEnabled(false);
        jPasswordFieldUsuSenha.setEnabled(false);
        jComboBoxUsuTpSenha.setEnabled(false);
        jButtonUsuSalvar.setEnabled(false);
        jButtonUsuCancelar.setEnabled(false);
        jButtonUsuEditar.setEnabled(false);
        jButtonUsuExcluir.setEnabled(false);
        jButtonUsuNovo.setEnabled(true);
        jButtonUsuPesquisa.setEnabled(true);
    }else{
    
        modu.setUsuNome(jFormattedTextFieldUsuNome.getText());
        modu.setUsuSenha(jPasswordFieldUsuSenha.getText());
        modu.setUsutipo((String) jComboBoxUsuTpSenha.getSelectedItem());
        control.Editar(modu);
        jFormattedTextFieldUsuNome.setText("");
        jTextFieldUsuPesquisa.setText("");
        jPasswordFieldUsuSenha.setText("");
        jPasswordFieldUsuConfSenha.setText("");
        jFormattedTextFieldUsuNome.setEnabled(false);
        jPasswordFieldUsuConfSenha.setEnabled(false);
        jPasswordFieldUsuSenha.setEnabled(false);
        jComboBoxUsuTpSenha.setEnabled(false);
        jButtonUsuSalvar.setEnabled(false);
        jButtonUsuCancelar.setEnabled(false);
        jButtonUsuEditar.setEnabled(false);
        jButtonUsuExcluir.setEnabled(false);
        jButtonUsuNovo.setEnabled(true);
        jButtonUsuPesquisa.setEnabled(true);
        }
    
        
    }//GEN-LAST:event_jButtonUsuSalvarActionPerformed

    private void jButtonUsuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuEditarActionPerformed
       
        
            flag=2;
            jFormattedTextFieldUsuNome.setEnabled(true);
            jPasswordFieldUsuConfSenha.setEnabled(true);
            jPasswordFieldUsuSenha.setEnabled(true);
            jComboBoxUsuTpSenha.setEnabled(true);
            jButtonUsuSalvar.setEnabled(true);
            jButtonUsuCancelar.setEnabled(true);
              
    }//GEN-LAST:event_jButtonUsuEditarActionPerformed

    private void jButtonUsuPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuPesquisaActionPerformed
       
            preencherTabela("select *from login order by usu_nome");
            modu.setUsupesq(jTextFieldUsuPesquisa.getText());
            BeansUsuario model = control.buscausuario(modu);
            jTextFieldusucod.setText(String .valueOf(model.getUsuCod()));
            jFormattedTextFieldUsuNome.setText(model.getUsuNome());
            jPasswordFieldUsuSenha.setText(model.getUsuSenha());
            jComboBoxUsuTpSenha.setSelectedItem(model.getUsutipo());
            jButtonUsuEditar.setEnabled(true);
            jButtonUsuExcluir.setEnabled(true);
            
    }//GEN-LAST:event_jButtonUsuPesquisaActionPerformed

    private void jFormattedTextFieldUsuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldUsuNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldUsuNomeActionPerformed

    private void jPasswordFieldUsuConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldUsuConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldUsuConfSenhaActionPerformed

    private void jButtonUsuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuExcluirActionPerformed
            
          int resposta=0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir?");
                if(resposta == JOptionPane.YES_OPTION){
                
                    modu.setUsuCod(Integer.parseInt(jTextFieldusucod.getText()));
                    control.Excluir(modu);
                    jFormattedTextFieldUsuNome.setText("");
                    jTextFieldUsuPesquisa.setText("");
                    jPasswordFieldUsuSenha.setText("");
                    jPasswordFieldUsuConfSenha.setText("");
                    jFormattedTextFieldUsuNome.setEnabled(false);
                    jPasswordFieldUsuConfSenha.setEnabled(false);
                    jPasswordFieldUsuSenha.setEnabled(false);
                    jComboBoxUsuTpSenha.setEnabled(false);
                    jButtonUsuSalvar.setEnabled(false);
                    jButtonUsuCancelar.setEnabled(false);
                    jButtonUsuEditar.setEnabled(false);
                    jButtonUsuExcluir.setEnabled(false);
                    jButtonUsuNovo.setEnabled(true);
                    jButtonUsuPesquisa.setEnabled(true);
                    
                    
                }
            
    }//GEN-LAST:event_jButtonUsuExcluirActionPerformed

    private void jButtonUsuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuCancelarActionPerformed
      
        jFormattedTextFieldUsuNome.setText("");
        jTextFieldUsuPesquisa.setText("");
        jPasswordFieldUsuSenha.setText("");
        jPasswordFieldUsuConfSenha.setText("");
        jFormattedTextFieldUsuNome.setEnabled(false);
        jPasswordFieldUsuConfSenha.setEnabled(false);
        jPasswordFieldUsuSenha.setEnabled(false);
        jComboBoxUsuTpSenha.setEnabled(false);
        jButtonUsuSalvar.setEnabled(false);
        jButtonUsuCancelar.setEnabled(false);
        jButtonUsuEditar.setEnabled(false);
        jButtonUsuExcluir.setEnabled(false);
        jButtonUsuNovo.setEnabled(true);
        jButtonUsuPesquisa.setEnabled(true);
        
    }//GEN-LAST:event_jButtonUsuCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] coluns = new String[]{"ID","nome","Tipo","Senha"};
        conex.Conexao();
        conex.Executasql(Sql);
        try{
        conex.rs.first();
        do{
            dados.add(new Object[]{conex.rs.getInt("usu_cod"),conex.rs.getString("usu_nome"),conex.rs.getString("usu_tipo"),conex.rs.getString("usu_senha")});
        }while(conex.rs.next());
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro ao preencher array list"+ex.getMessage());
        
        } 
        ModeloTabelaCli modelo = new ModeloTabelaCli(dados, coluns);
        jTableUsuPesquisa.setModel(modelo);
        jTableUsuPesquisa.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableUsuPesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuPesquisa.getColumnModel().getColumn(1).setPreferredWidth(102);
        jTableUsuPesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTableUsuPesquisa.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTableUsuPesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuPesquisa.getColumnModel().getColumn(3).setPreferredWidth(245);
        jTableUsuPesquisa.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuPesquisa.getTableHeader().setReorderingAllowed(false);
        jTableUsuPesquisa.setAutoResizeMode(jTableUsuPesquisa.AUTO_RESIZE_OFF);
        jTableUsuPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.Desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonUsuCancelar;
    private javax.swing.JButton jButtonUsuEditar;
    private javax.swing.JButton jButtonUsuExcluir;
    private javax.swing.JButton jButtonUsuNovo;
    private javax.swing.JButton jButtonUsuPesquisa;
    private javax.swing.JButton jButtonUsuSalvar;
    private javax.swing.JComboBox<String> jComboBoxUsuTpSenha;
    private javax.swing.JFormattedTextField jFormattedTextFieldUsuNome;
    private javax.swing.JLabel jLabelCadEntrega;
    private javax.swing.JLabel jLabelEntUsuTpSenha;
    private javax.swing.JLabel jLabelFundoEntrega;
    private javax.swing.JLabel jLabelUsuConfSenha;
    private javax.swing.JLabel jLabelUsuNome;
    private javax.swing.JLabel jLabelUsuSenha;
    private javax.swing.JLabel jLabelusucod;
    private javax.swing.JPanel jPanelCadEntrega;
    private javax.swing.JPasswordField jPasswordFieldUsuConfSenha;
    private javax.swing.JPasswordField jPasswordFieldUsuSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuPesquisa;
    private javax.swing.JTextField jTextFieldUsuPesquisa;
    private javax.swing.JTextField jTextFieldusucod;
    // End of variables declaration//GEN-END:variables
}
