/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoFrota;
import modeloBeans.BeansFrota;
import modeloBeans.ModeloTabelaFrota;





/**
 *
 * @author Buzato
 */
public class CadastroFrota extends javax.swing.JFrame {

        BeansFrota modfr = new BeansFrota();
        DaoFrota control = new DaoFrota();
        ConexaoBD conex = new ConexaoBD();
        int flag=0;
        
    
    public CadastroFrota() {
        initComponents();
        preencherTabela("select *from frota order by fr_marca");
        jTextFieldFrCod.setEnabled(false);
        jFormattedTextFrTipo.setEnabled(false);
        jTextFieldFrModelo.setEnabled(false);        
        jTextFieldFrLocal.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldFrCor.setEnabled(false); 
        jTextFieldFrKM.setEnabled(false);
        jComboBoxFrUF.setEnabled(false); 
        jFormattedTextFieldFrRenavan.setEnabled(false); 
        jFormattedTextFrLicen.setEnabled(false);  
        jFormattedTextFieldFrChassi.setEnabled(false);
        jComboBoxFrComb.setEnabled(false);
        jButtonFrNovo.setEnabled(true);
        jButtonFrSalvar.setEnabled(false);
        jButtonFrCancelar.setEnabled(false);
        jButtonFrEditar.setEnabled(false);
        jButtonFrExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadFrota = new javax.swing.JPanel();
        jLabelFrTipo = new javax.swing.JLabel();
        jLabelFrModelo = new javax.swing.JLabel();
        jLabelFrLocal = new javax.swing.JLabel();
        jLabelFrLicen = new javax.swing.JLabel();
        jLabelFrChassi = new javax.swing.JLabel();
        jLabelFrPlaca = new javax.swing.JLabel();
        jTextFieldFrModelo = new javax.swing.JTextField();
        jTextFieldFrLocal = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelFrRenavan = new javax.swing.JLabel();
        jLabelFrCor = new javax.swing.JLabel();
        jTextFieldFrCor = new javax.swing.JTextField();
        jLabelFrKM = new javax.swing.JLabel();
        jTextFieldFrKM = new javax.swing.JTextField();
        jLabelFrUF = new javax.swing.JLabel();
        jComboBoxFrUF = new javax.swing.JComboBox<>();
        jButtonFrNovo = new javax.swing.JButton();
        jButtonFrSalvar = new javax.swing.JButton();
        jButtonFrCancelar = new javax.swing.JButton();
        jButtonFrEditar = new javax.swing.JButton();
        jButtonFrExcluir = new javax.swing.JButton();
        jTextFieldFrPesq = new javax.swing.JTextField();
        jButtonFrPesq = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliPesq = new javax.swing.JTable();
        jFormattedTextFrTipo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFrRenavan = new javax.swing.JFormattedTextField();
        jFormattedTextFrLicen = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFrChassi = new javax.swing.JFormattedTextField();
        jLabelFrcomb = new javax.swing.JLabel();
        jComboBoxFrComb = new javax.swing.JComboBox<>();
        jTextFieldFrCod = new javax.swing.JTextField();
        jLabelCodFrota = new javax.swing.JLabel();
        jLabelFundoFrota = new javax.swing.JLabel();
        jLabelCadFrota = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelCadFrota.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadFrota.setLayout(null);

        jLabelFrTipo.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrTipo.setText("Tipo Veiculo.:");
        jPanelCadFrota.add(jLabelFrTipo);
        jLabelFrTipo.setBounds(120, 70, 90, 30);

        jLabelFrModelo.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrModelo.setText("Marca / Modelo.:");
        jPanelCadFrota.add(jLabelFrModelo);
        jLabelFrModelo.setBounds(100, 40, 130, 30);

        jLabelFrLocal.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrLocal.setText("LOcal.:");
        jPanelCadFrota.add(jLabelFrLocal);
        jLabelFrLocal.setBounds(160, 101, 50, 30);

        jLabelFrLicen.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrLicen.setText("Data Licenciamento.:");
        jPanelCadFrota.add(jLabelFrLicen);
        jLabelFrLicen.setBounds(310, 160, 140, 30);

        jLabelFrChassi.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrChassi.setText("Chassi.:");
        jPanelCadFrota.add(jLabelFrChassi);
        jLabelFrChassi.setBounds(590, 160, 100, 30);

        jLabelFrPlaca.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrPlaca.setText("Placa.:");
        jPanelCadFrota.add(jLabelFrPlaca);
        jLabelFrPlaca.setBounds(160, 130, 50, 30);
        jPanelCadFrota.add(jTextFieldFrModelo);
        jTextFieldFrModelo.setBounds(210, 40, 330, 30);
        jPanelCadFrota.add(jTextFieldFrLocal);
        jTextFieldFrLocal.setBounds(210, 100, 330, 30);

        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(210, 130, 150, 30);

        jLabelFrRenavan.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrRenavan.setText("RENAVAN.:");
        jPanelCadFrota.add(jLabelFrRenavan);
        jLabelFrRenavan.setBounds(140, 160, 70, 30);

        jLabelFrCor.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrCor.setText("Cor.:");
        jPanelCadFrota.add(jLabelFrCor);
        jLabelFrCor.setBounds(370, 130, 60, 30);
        jPanelCadFrota.add(jTextFieldFrCor);
        jTextFieldFrCor.setBounds(410, 130, 130, 30);

        jLabelFrKM.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrKM.setText("KM Inicial.:");
        jPanelCadFrota.add(jLabelFrKM);
        jLabelFrKM.setBounds(570, 140, 80, 13);
        jPanelCadFrota.add(jTextFieldFrKM);
        jTextFieldFrKM.setBounds(650, 130, 140, 30);

        jLabelFrUF.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrUF.setText("UF.:");
        jPanelCadFrota.add(jLabelFrUF);
        jLabelFrUF.setBounds(620, 100, 30, 30);

        jComboBoxFrUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM\t ", "\tBA\t ", "\tCE\t ", "\tDF\t ", "\tES\t ", "\tGO\t ", "\tMA\t ", "\tMT\t ", "\tMS\t ", "\tMG\t ", "\tPA\t ", "\tPB\t ", "\tPR\t ", "\tPE\t ", "\tPI\t ", "\tRJ\t ", "\tRN\t ", "\tRS\t ", "\tRO\t ", "\tRR\t ", "\tSC\t ", "\tSP\t ", "\tSE\t ", "\tTO" }));
        jPanelCadFrota.add(jComboBoxFrUF);
        jComboBoxFrUF.setBounds(650, 100, 60, 30);

        jButtonFrNovo.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jButtonFrNovo.setText("Novo");
        jButtonFrNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrNovoActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrNovo);
        jButtonFrNovo.setBounds(80, 220, 110, 30);

        jButtonFrSalvar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cloud 2.png"))); // NOI18N
        jButtonFrSalvar.setText("Salvar");
        jButtonFrSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrSalvarActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrSalvar);
        jButtonFrSalvar.setBounds(80, 260, 110, 30);

        jButtonFrCancelar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButtonFrCancelar.setText("Cancelar");
        jButtonFrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrCancelarActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrCancelar);
        jButtonFrCancelar.setBounds(80, 300, 110, 30);

        jButtonFrEditar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pencil.png"))); // NOI18N
        jButtonFrEditar.setText("Editar");
        jButtonFrEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrEditarActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrEditar);
        jButtonFrEditar.setBounds(80, 340, 110, 30);

        jButtonFrExcluir.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Remove.png"))); // NOI18N
        jButtonFrExcluir.setText("Excluir");
        jButtonFrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrExcluirActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrExcluir);
        jButtonFrExcluir.setBounds(80, 380, 110, 30);
        jPanelCadFrota.add(jTextFieldFrPesq);
        jTextFieldFrPesq.setBounds(230, 230, 440, 30);

        jButtonFrPesq.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jButtonFrPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search 1.png"))); // NOI18N
        jButtonFrPesq.setText("Pesquisar");
        jButtonFrPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrPesqActionPerformed(evt);
            }
        });
        jPanelCadFrota.add(jButtonFrPesq);
        jButtonFrPesq.setBounds(680, 230, 120, 30);

        jTableCliPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCliPesq);

        jPanelCadFrota.add(jScrollPane1);
        jScrollPane1.setBounds(230, 260, 620, 150);
        jPanelCadFrota.add(jFormattedTextFrTipo);
        jFormattedTextFrTipo.setBounds(210, 70, 330, 30);
        jPanelCadFrota.add(jFormattedTextFieldFrRenavan);
        jFormattedTextFieldFrRenavan.setBounds(210, 160, 90, 30);
        jPanelCadFrota.add(jFormattedTextFrLicen);
        jFormattedTextFrLicen.setBounds(450, 160, 90, 30);
        jPanelCadFrota.add(jFormattedTextFieldFrChassi);
        jFormattedTextFieldFrChassi.setBounds(650, 160, 140, 30);

        jLabelFrcomb.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelFrcomb.setText("Combustivel.:");
        jPanelCadFrota.add(jLabelFrcomb);
        jLabelFrcomb.setBounds(550, 80, 100, 20);

        jComboBoxFrComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Alcool", "Diesel", "Flex" }));
        jPanelCadFrota.add(jComboBoxFrComb);
        jComboBoxFrComb.setBounds(650, 70, 90, 30);
        jPanelCadFrota.add(jTextFieldFrCod);
        jTextFieldFrCod.setBounds(209, 10, 100, 30);

        jLabelCodFrota.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelCodFrota.setText("Cod Frota.:");
        jPanelCadFrota.add(jLabelCodFrota);
        jLabelCodFrota.setBounds(130, 10, 80, 30);

        jLabelFundoFrota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos-para-fotos-verde (3).jpg"))); // NOI18N
        jPanelCadFrota.add(jLabelFundoFrota);
        jLabelFundoFrota.setBounds(0, 0, 1080, 440);

        getContentPane().add(jPanelCadFrota);
        jPanelCadFrota.setBounds(30, 40, 1080, 440);

        jLabelCadFrota.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabelCadFrota.setText("Cadastro de Frota");
        getContentPane().add(jLabelCadFrota);
        jLabelCadFrota.setBounds(470, 10, 190, 19);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1083, 10, 20, 25);

        setSize(new java.awt.Dimension(1130, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    private void jButtonFrNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrNovoActionPerformed
     
        flag=1;
        
        jFormattedTextFrTipo.setEnabled(true);
        jTextFieldFrModelo.setEnabled(true);        
        jTextFieldFrLocal.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jTextFieldFrCor.setEnabled(true); 
        jTextFieldFrKM.setEnabled(true);
        jComboBoxFrUF.setEnabled(true); 
        jComboBoxFrComb.setEnabled(true);
        jFormattedTextFieldFrRenavan.setEnabled(true); 
        jFormattedTextFrLicen.setEnabled(true);  
        jFormattedTextFieldFrChassi.setEnabled(true);
        jTextFieldFrPesq.setEnabled(false);
        jButtonFrNovo.setEnabled(false);
        jButtonFrSalvar.setEnabled(true);
        jButtonFrCancelar.setEnabled(true);
        jButtonFrEditar.setEnabled(false);
        jButtonFrExcluir.setEnabled(false);
        jButtonFrPesq.setEnabled(false);
                
    }//GEN-LAST:event_jButtonFrNovoActionPerformed

    private void jButtonFrSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrSalvarActionPerformed
       
        if(flag == 1){
        modfr.setFr_tpveiculo(jFormattedTextFrTipo.getText());
        modfr.setFr_marca(jTextFieldFrModelo.getText());
        modfr.setFr_combustivel((String)jComboBoxFrComb.getSelectedItem());
        modfr.setFr_local(jTextFieldFrLocal.getText());
        modfr.setFr_uf((String)jComboBoxFrUF.getSelectedItem());
        modfr.setFr_placa(jTextFieldPlaca.getText());
        modfr.setFr_cor( jTextFieldFrCor.getText());
        modfr.setFr_kmini(jTextFieldFrKM.getText());
        modfr.setFr_renavan(jFormattedTextFieldFrRenavan.getText());
        modfr.setFr_dtlinc(jFormattedTextFrLicen.getText());
        modfr.setFr_chassi(jFormattedTextFieldFrChassi.getText());
        control.Salvar(modfr);
        jTextFieldFrCod.setText("");
        jFormattedTextFrTipo.setText("");
        jTextFieldFrModelo.setText("");
        jTextFieldFrLocal.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldFrCor.setText("");
        jTextFieldFrKM.setText("");
        jFormattedTextFieldFrRenavan.setText("");
        jFormattedTextFrLicen.setText("");
        jFormattedTextFieldFrChassi.setText("");
        jFormattedTextFrTipo.setEnabled(false);
        jTextFieldFrModelo.setEnabled(false);
        jTextFieldFrLocal.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldFrCor.setEnabled(false);
        jTextFieldFrKM.setEnabled(false);
        jFormattedTextFieldFrRenavan.setEnabled(false);
        jFormattedTextFrLicen.setEnabled(false);
        jFormattedTextFieldFrChassi.setEnabled(false);
        jTextFieldFrPesq.setEnabled(true);
        jComboBoxFrUF.setEnabled(false);
        jButtonFrSalvar.setEnabled(false);
        jButtonFrCancelar.setEnabled(false);
        jButtonFrNovo.setEnabled(true);
        jButtonFrPesq.setEnabled(true);
        }else{
            
        modfr.setFr_tpveiculo(jFormattedTextFrTipo.getText());
        modfr.setFr_marca(jTextFieldFrModelo.getText());
        modfr.setFr_combustivel((String)jComboBoxFrComb.getSelectedItem());
        modfr.setFr_local(jTextFieldFrLocal.getText());
        modfr.setFr_uf((String)jComboBoxFrUF.getSelectedItem());
        modfr.setFr_placa(jTextFieldPlaca.getText());
        modfr.setFr_cor( jTextFieldFrCor.getText());
        modfr.setFr_kmini(jTextFieldFrKM.getText());
        modfr.setFr_renavan(jFormattedTextFieldFrRenavan.getText());
        modfr.setFr_dtlinc(jFormattedTextFrLicen.getText());
        modfr.setFr_chassi(jFormattedTextFieldFrChassi.getText());
        control.Editar(modfr);
         jTextFieldFrCod.setText("");
        jFormattedTextFrTipo.setText("");
        jTextFieldFrModelo.setText("");
        jTextFieldFrLocal.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldFrCor.setText("");
        jTextFieldFrKM.setText("");
        jFormattedTextFieldFrRenavan.setText("");
        jFormattedTextFrLicen.setText("");
        jFormattedTextFieldFrChassi.setText("");
        jFormattedTextFrTipo.setEnabled(false);
        jTextFieldFrModelo.setEnabled(false);
        jTextFieldFrLocal.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldFrCor.setEnabled(false);
        jTextFieldFrKM.setEnabled(false);
        jFormattedTextFieldFrRenavan.setEnabled(false);
        jFormattedTextFrLicen.setEnabled(false);
        jFormattedTextFieldFrChassi.setEnabled(false);
        jTextFieldFrPesq.setEnabled(true);
        jComboBoxFrUF.setEnabled(false);
        jComboBoxFrComb.setEditable(false);
        jButtonFrSalvar.setEnabled(false);
        jButtonFrCancelar.setEnabled(false);
        jButtonFrNovo.setEnabled(true);
        jButtonFrPesq.setEnabled(true);
        }
    
        
    }//GEN-LAST:event_jButtonFrSalvarActionPerformed

    private void jButtonFrEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrEditarActionPerformed

             flag=2;
        
        jFormattedTextFrTipo.setEnabled(true);
        jTextFieldFrModelo.setEnabled(true);
        jTextFieldFrLocal.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jTextFieldFrCor.setEnabled(true);
        jTextFieldFrKM.setEnabled(true);
        jFormattedTextFieldFrRenavan.setEnabled(true);
        jFormattedTextFrLicen.setEnabled(true);
        jFormattedTextFieldFrChassi.setEnabled(true);
        jTextFieldFrPesq.setEnabled(true);
        jComboBoxFrUF.setEnabled(true);
        jComboBoxFrComb.setEnabled(true);
        jTableCliPesq.setEnabled(false);
        jButtonFrEditar.setEnabled(false);
        jButtonFrExcluir.setEnabled(false);
        jButtonFrSalvar.setEnabled(true);
        jButtonFrNovo.setEnabled(false);
        jButtonFrCancelar.setEnabled(true);
        jButtonFrPesq.setEnabled(false);
        
        
    }//GEN-LAST:event_jButtonFrEditarActionPerformed

    private void jButtonFrPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrPesqActionPerformed
       
            preencherTabela("select *from frota order by fr_marca");
            modfr.setFr_pesquisa(jTextFieldFrPesq.getText());
            BeansFrota model = control.buscaFrota(modfr);
            jTextFieldFrCod.setText(String.valueOf(model.getCod_forta()));
            jFormattedTextFrTipo.setText(model.getFr_tpveiculo());
            jTextFieldFrModelo.setText(model.getFr_marca());
            jComboBoxFrComb.setSelectedItem(model.getFr_combustivel());
            jTextFieldFrLocal.setText(model.getFr_local());
            jComboBoxFrUF.setSelectedItem(model.getFr_uf());
            jTextFieldPlaca.setText(model.getFr_placa());
            jTextFieldFrCor.setText(model.getFr_cor());
            jTextFieldFrKM.setText(model.getFr_kmini());
            jFormattedTextFieldFrRenavan.setText(model.getFr_renavan());
            jFormattedTextFrLicen.setText(model.getFr_dtlinc());
            jFormattedTextFieldFrChassi.setText(model.getFr_chassi());
            jButtonFrEditar.setEnabled(true);
            jButtonFrExcluir.setEnabled(true);
            jButtonFrCancelar.setEnabled(true);
            
            
    }//GEN-LAST:event_jButtonFrPesqActionPerformed

    private void jButtonFrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrCancelarActionPerformed
            
            jFormattedTextFrTipo.setText("");
            jTextFieldFrModelo.setText("");
            jTextFieldFrLocal.setText("");
            jTextFieldPlaca.setText("");
            jTextFieldFrCor.setText("");
            jTextFieldFrKM.setText("");
            jFormattedTextFieldFrRenavan.setText("");
            jFormattedTextFrLicen.setText("");
            jFormattedTextFieldFrChassi.setText("");
            jTextFieldFrPesq.setText("");
            jTextFieldFrPesq.setEnabled(true);
            jFormattedTextFrTipo.setEnabled(false);
            jTextFieldFrModelo.setEnabled(false);
            jTextFieldFrLocal.setEnabled(false);
            jTextFieldPlaca.setEnabled(false);
            jTextFieldFrCor.setEnabled(false);
            jTextFieldFrKM.setEnabled(false);
            jFormattedTextFieldFrRenavan.setEnabled(false);
            jFormattedTextFrLicen.setEnabled(false);
            jFormattedTextFieldFrChassi.setEnabled(false);
            jComboBoxFrUF.setEnabled(false);
            jButtonFrSalvar.setEnabled(false);
            jButtonFrNovo.setEnabled(true);
            jButtonFrCancelar.setEnabled(false);
            jButtonFrPesq.setEnabled(true);
            jButtonFrEditar.setEnabled(false);
            jButtonFrExcluir.setEnabled(false);
    
            
            
    }//GEN-LAST:event_jButtonFrCancelarActionPerformed

    private void jButtonFrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrExcluirActionPerformed
 
            int resposta=0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir?");
                if(resposta == JOptionPane.YES_OPTION){
                
                    modfr.setCod_forta(Integer.parseInt(jTextFieldFrCod.getText()));
                    control.Excluir(modfr);
                     jFormattedTextFrTipo.setText("");
                jFormattedTextFrTipo.setText("");
                jTextFieldFrModelo.setText("");
                jTextFieldFrLocal.setText("");
                jTextFieldPlaca.setText("");
                jTextFieldFrCor.setText("");
                jTextFieldFrKM.setText("");
                jFormattedTextFieldFrRenavan.setText("");
                jFormattedTextFrLicen.setText("");
                jFormattedTextFieldFrChassi.setText("");
                jTextFieldFrPesq.setText("");
                jTextFieldFrCod.setText("");
                    jFormattedTextFrTipo.setEnabled(false);
                    jTextFieldFrModelo.setEnabled(false);
                    jTextFieldFrLocal.setEnabled(false);
                    jTextFieldPlaca.setEnabled(false);
                    jTextFieldFrCor.setEnabled(false);
                    jTextFieldFrKM.setEnabled(false);
                    jFormattedTextFieldFrRenavan.setEnabled(false);
                    jFormattedTextFrLicen.setEnabled(false);
                    jFormattedTextFieldFrChassi.setEnabled(false);
                    jComboBoxFrUF.setEnabled(false);
                    jComboBoxFrComb.setEnabled(false);
                        jButtonFrEditar.setEnabled(false);
                        jButtonFrExcluir.setEnabled(false);
                        jButtonFrSalvar.setEnabled(false);
                        jButtonFrNovo.setEnabled(true);
                        jButtonFrCancelar.setEnabled(false);
                        jButtonFrPesq.setEnabled(true);
                    
                    
                }
    }//GEN-LAST:event_jButtonFrExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] coluns = new String[]{"ID Frota","Modelo/Marca","Tipo Veiculo","Combustivel"};
        conex.Conexao();
        conex.Executasql(Sql);
        try{
        conex.rs.first();
        do{
            dados.add(new Object[]{conex.rs.getInt("cod_forta"),conex.rs.getString("fr_marca"),conex.rs.getString("fr_tpveiculo"),conex.rs.getString("fr_combustivel")});
        }while(conex.rs.next());
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro ao preencher array list"+ex.getMessage());
        
        } 
            ModeloTabelaFrota modelo = new ModeloTabelaFrota(dados, coluns);
        jTableCliPesq.setModel(modelo);
        jTableCliPesq.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableCliPesq.getColumnModel().getColumn(0).setResizable(false);
        jTableCliPesq.getColumnModel().getColumn(1).setPreferredWidth(102);
        jTableCliPesq.getColumnModel().getColumn(1).setResizable(false);
        jTableCliPesq.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTableCliPesq.getColumnModel().getColumn(2).setResizable(false);
        jTableCliPesq.getColumnModel().getColumn(3).setPreferredWidth(220);
        jTableCliPesq.getColumnModel().getColumn(3).setResizable(false);
        jTableCliPesq.getTableHeader().setReorderingAllowed(false);
        jTableCliPesq.setAutoResizeMode(jTableCliPesq.AUTO_RESIZE_OFF);
        jTableCliPesq.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.Desconecta();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFrota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFrCancelar;
    private javax.swing.JButton jButtonFrEditar;
    private javax.swing.JButton jButtonFrExcluir;
    private javax.swing.JButton jButtonFrNovo;
    private javax.swing.JButton jButtonFrPesq;
    private javax.swing.JButton jButtonFrSalvar;
    private javax.swing.JComboBox<String> jComboBoxFrComb;
    private javax.swing.JComboBox<String> jComboBoxFrUF;
    private javax.swing.JFormattedTextField jFormattedTextFieldFrChassi;
    private javax.swing.JFormattedTextField jFormattedTextFieldFrRenavan;
    private javax.swing.JFormattedTextField jFormattedTextFrLicen;
    private javax.swing.JFormattedTextField jFormattedTextFrTipo;
    private javax.swing.JLabel jLabelCadFrota;
    private javax.swing.JLabel jLabelCodFrota;
    private javax.swing.JLabel jLabelFrChassi;
    private javax.swing.JLabel jLabelFrCor;
    private javax.swing.JLabel jLabelFrKM;
    private javax.swing.JLabel jLabelFrLicen;
    private javax.swing.JLabel jLabelFrLocal;
    private javax.swing.JLabel jLabelFrModelo;
    private javax.swing.JLabel jLabelFrPlaca;
    private javax.swing.JLabel jLabelFrRenavan;
    private javax.swing.JLabel jLabelFrTipo;
    private javax.swing.JLabel jLabelFrUF;
    private javax.swing.JLabel jLabelFrcomb;
    private javax.swing.JLabel jLabelFundoFrota;
    private javax.swing.JPanel jPanelCadFrota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliPesq;
    private javax.swing.JTextField jTextFieldFrCod;
    private javax.swing.JTextField jTextFieldFrCor;
    private javax.swing.JTextField jTextFieldFrKM;
    private javax.swing.JTextField jTextFieldFrLocal;
    private javax.swing.JTextField jTextFieldFrModelo;
    private javax.swing.JTextField jTextFieldFrPesq;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
