/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import controle.Transparencia;
import modeloConection.ConexaoBD;

/**
 *
 * @author Buzato
 */
public class Splash extends javax.swing.JFrame {

         ConexaoBD conecta = new ConexaoBD();
        
         
    
    public Splash() {
        Transparencia trans = new Transparencia();
        trans.aplTransparencia(this);
       conecta.Conexao();
        
       initComponents();
       //com.sun.awt.AWTUtilities.setWindowOpacity(Splash.this, 0.5f);
              
        new Thread()
        {
            public void run()
            {
                    
                    
                    
                int i;
             
              
                for(i=0; i<101; i++)
                {
                    try {
                        sleep(80);
                        jProgressBarSplash.setValue(i);
                        
                         if(jProgressBarSplash.getValue() <= 40)
                    {
                        jLabelSplash.setText("Carregando Banco de Dados.....");
                    }
                         else if(jProgressBarSplash.getValue() <=60)
                         {
                             jLabelSplash.setText("Carregando Tabelas.....");
                         }
                         else if(jProgressBarSplash.getValue() <=80)
                         {
                             jLabelSplash.setText("Carregando Gambiarras.....");
                         }
                         else if(jProgressBarSplash.getValue() <=90)
                         {
                             jLabelSplash.setText("Carregando Sistema.....");
                         }
                        
                    
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                  Login tela = new Login();
                  tela.setVisible(true);
                  dispose();
                  
            }

           private void setVisble(boolean b) {
               throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           }
          
          
            
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSplash = new javax.swing.JLabel();
        jProgressBarSplash = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabelSplash.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        getContentPane().add(jLabelSplash);
        jLabelSplash.setBounds(300, 250, 200, 30);

        jProgressBarSplash.setStringPainted(true);
        getContentPane().add(jProgressBarSplash);
        jProgressBarSplash.setBounds(270, 230, 216, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoNew2.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 520, 270);

        setSize(new java.awt.Dimension(790, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSplash;
    private javax.swing.JProgressBar jProgressBarSplash;
    // End of variables declaration//GEN-END:variables
}
