/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;



import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeloConection.ConexaoBD;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Buzato
 */
public class TelaPrincipal extends javax.swing.JFrame {

       ConexaoBD conecta = new ConexaoBD();

    
    public TelaPrincipal(String usuario) {
             
        initComponents();
         jLabelUsuarioLogado.setText(usuario);
         conecta.Conexao();
        
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    

   

    

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelFundoBemVindo = new javax.swing.JPanel();
        jButtonPainelFuncionarios = new javax.swing.JButton();
        jButtonPainelClientes = new javax.swing.JButton();
        jButtonPainelMotorista = new javax.swing.JButton();
        jLabelPainelClientes = new javax.swing.JLabel();
        jLabelPainelFuncionario = new javax.swing.JLabel();
        jLabelPainelMotorista = new javax.swing.JLabel();
        jLabellogado = new javax.swing.JLabel();
        jLabelUsuarioLogado = new javax.swing.JLabel();
        jLabelFundoPanelBemVindo = new javax.swing.JLabel();
        jLabelTituloTrans = new javax.swing.JLabel();
        jLabellogoGrande = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadClientes = new javax.swing.JMenuItem();
        jMenuItemCadFunc = new javax.swing.JMenuItem();
        jMenuItemCadMoto = new javax.swing.JMenuItem();
        jMenuItemCadUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRelaEntrega = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setClosable(true);
        jInternalFrameBemVindo.setIconifiable(true);
        jInternalFrameBemVindo.setMaximizable(true);
        jInternalFrameBemVindo.setTitle("Bem - Vindo");
        jInternalFrameBemVindo.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelFundoBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelFundoBemVindo.setLayout(null);

        jButtonPainelFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes2.png"))); // NOI18N
        jButtonPainelFuncionarios.setPreferredSize(new java.awt.Dimension(70, 20));
        jButtonPainelFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPainelFuncionariosActionPerformed(evt);
            }
        });
        jPanelFundoBemVindo.add(jButtonPainelFuncionarios);
        jButtonPainelFuncionarios.setBounds(30, 80, 130, 110);

        jButtonPainelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios2.png"))); // NOI18N
        jButtonPainelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPainelClientesActionPerformed(evt);
            }
        });
        jPanelFundoBemVindo.add(jButtonPainelClientes);
        jButtonPainelClientes.setBounds(200, 80, 130, 110);

        jButtonPainelMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/motorista2.gif"))); // NOI18N
        jButtonPainelMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPainelMotoristaActionPerformed(evt);
            }
        });
        jPanelFundoBemVindo.add(jButtonPainelMotorista);
        jButtonPainelMotorista.setBounds(380, 80, 130, 110);

        jLabelPainelClientes.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelPainelClientes.setText(" Clientes");
        jPanelFundoBemVindo.add(jLabelPainelClientes);
        jLabelPainelClientes.setBounds(230, 50, 70, 20);

        jLabelPainelFuncionario.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelPainelFuncionario.setText(" Funcionário");
        jPanelFundoBemVindo.add(jLabelPainelFuncionario);
        jLabelPainelFuncionario.setBounds(50, 50, 100, 20);

        jLabelPainelMotorista.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelPainelMotorista.setText("Frotas");
        jPanelFundoBemVindo.add(jLabelPainelMotorista);
        jLabelPainelMotorista.setBounds(420, 50, 70, 20);

        jLabellogado.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabellogado.setForeground(new java.awt.Color(204, 0, 0));
        jLabellogado.setText("Usuáriio .:");
        jPanelFundoBemVindo.add(jLabellogado);
        jLabellogado.setBounds(10, 230, 70, 20);

        jLabelUsuarioLogado.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabelUsuarioLogado.setText("label5");
        jPanelFundoBemVindo.add(jLabelUsuarioLogado);
        jLabelUsuarioLogado.setBounds(90, 230, 190, 20);

        jLabelFundoPanelBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.png"))); // NOI18N
        jPanelFundoBemVindo.add(jLabelFundoPanelBemVindo);
        jLabelFundoPanelBemVindo.setBounds(0, 0, 880, 320);

        jInternalFrameBemVindo.getContentPane().add(jPanelFundoBemVindo);
        jPanelFundoBemVindo.setBounds(-10, 50, 880, 320);

        jLabelTituloTrans.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabelTituloTrans.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTrans.setText("Mercurio Tranporte Express");
        jInternalFrameBemVindo.getContentPane().add(jLabelTituloTrans);
        jLabelTituloTrans.setBounds(310, 0, 480, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(360, 180, 880, 330);

        jLabellogoGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo-teste.gif"))); // NOI18N
        getContentPane().add(jLabellogoGrande);
        jLabellogoGrande.setBounds(130, 180, 1260, 520);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abstract-background-green-lines-2800x1050.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 1440, 900);

        jMenuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pencil.png"))); // NOI18N
        jMenuCadastros.setText("Arquivos");

        jMenuItemCadClientes.setText("Cadastro de Clientes");
        jMenuItemCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadClientes);

        jMenuItemCadFunc.setText("Cadastro de Funcionários");
        jMenuItemCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadFunc);

        jMenuItemCadMoto.setText("Cadastro de Frotas");
        jMenuItemCadMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMotoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadMoto);

        jMenuItemCadUsuario.setText("Cadastro de Usuários");
        jMenuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuario);

        jMenuBarPrincipal.add(jMenuCadastros);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Images.png"))); // NOI18N
        jMenu2.setText("Relatórios");

        jMenuItemRelaEntrega.setText("Entrega");
        jMenuItemRelaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelaEntregaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelaEntrega);

        jMenuBarPrincipal.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Wrench.png"))); // NOI18N
        jMenu1.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem - Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTelaBemVindo);

        jMenuBarPrincipal.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cross.png"))); // NOI18N
        jMenu3.setText("Sair");

        jMenuItem1.setText("Sair do Sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenu3);

        setJMenuBar(jMenuBarPrincipal);

        setSize(new java.awt.Dimension(1440, 900));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
int resposta=0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente Sair do Sistema?");
                if(resposta == JOptionPane.YES_OPTION){        
        conecta.Desconecta();
        System.exit(0);
                }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        
         jInternalFrameBemVindo.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClientesActionPerformed
        // TODO add your handling code here:
            CadastroClientes telCadCli = new CadastroClientes();
            telCadCli.setVisible(true);
            
        
    }//GEN-LAST:event_jMenuItemCadClientesActionPerformed

    private void jButtonPainelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPainelClientesActionPerformed
        CadastroClientes telCadCli = new CadastroClientes();
            telCadCli.setVisible(true);
    }//GEN-LAST:event_jButtonPainelClientesActionPerformed

    private void jButtonPainelFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPainelFuncionariosActionPerformed
        
              
            CadastroFuncionario telfunc = new CadastroFuncionario();
            telfunc.setVisible(true);                                         
    }//GEN-LAST:event_jButtonPainelFuncionariosActionPerformed

    private void jMenuItemCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncActionPerformed
        
            CadastroFuncionario telfunc = new CadastroFuncionario();
            telfunc.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncActionPerformed

    private void jButtonPainelMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPainelMotoristaActionPerformed
 
        CadastroFrota tela = new CadastroFrota();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonPainelMotoristaActionPerformed

    private void jMenuItemCadMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMotoActionPerformed
        
        CadastroFrota tela = new CadastroFrota();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMotoActionPerformed

    private void jMenuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuarioActionPerformed
        
           try {
               conecta.Executasql("select *from login where usu_nome='"+jLabelUsuarioLogado.getText()+"'");
               conecta.rs.first();
               if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                   
                   CadastroUsuarios tela = new CadastroUsuarios();
                   tela.setVisible(true);
               }else{
                   
                   JOptionPane.showMessageDialog(rootPane, "Voce não tem permição para esssa opção!!\nContate o adiministrador do sistema!!");
               }
           } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Voce não tem permição para esssa opção!!\nContate o adiministrador do sistema!!");           }
        
    }//GEN-LAST:event_jMenuItemCadUsuarioActionPerformed

    private void jMenuItemRelaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelaEntregaActionPerformed
        try{
        conecta.Executasql("select *from agenda");
        JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("iReport/RelatorioAgenda.jasper", new HashMap(), relatResul);
        JasperViewer jv = new JasperViewer(jpPrint);
        jv.setVisible(true);
        jv.dispose();
        jv.toFront();
        
        }catch(JRException ex){
            JOptionPane.showMessageDialog(null, "Erro ao carregar relatorio!!"+ex);
        }
        
    }//GEN-LAST:event_jMenuItemRelaEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPainelClientes;
    private javax.swing.JButton jButtonPainelFuncionarios;
    private javax.swing.JButton jButtonPainelMotorista;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabelFundoPanelBemVindo;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelClientes;
    private javax.swing.JLabel jLabelPainelFuncionario;
    private javax.swing.JLabel jLabelPainelMotorista;
    private javax.swing.JLabel jLabelTituloTrans;
    private javax.swing.JLabel jLabelUsuarioLogado;
    private javax.swing.JLabel jLabellogado;
    private javax.swing.JLabel jLabellogoGrande;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCadClientes;
    private javax.swing.JMenuItem jMenuItemCadFunc;
    private javax.swing.JMenuItem jMenuItemCadMoto;
    private javax.swing.JMenuItem jMenuItemCadUsuario;
    private javax.swing.JMenuItem jMenuItemRelaEntrega;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JPanel jPanelFundoBemVindo;
    // End of variables declaration//GEN-END:variables
}
